server:
  port: 8005

spring:
  application:
    name: contest-service
  profiles:
    active: dev
  config:
    import:
      - optional:nacos:common.yaml
      - optional:nacos:jwt.yaml
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yaml
  cloud:
    nacos:
      server-addr: lirendada.art:8848
      discovery:
        server-addr: lirendada.art:8848
        namespace: ceaffba5-fad9-4149-a71a-f77956f10897
      config:
        server-addr: lirendada.art:8848
        namespace: ceaffba5-fad9-4149-a71a-f77956f10897
        file-extension: yaml