server:
  port: 8001

spring:
  application:
    name: job-service
  profiles:
    active: dev
  config:
    import:
      - optional:nacos:common.yaml
      - optional:nacos:jwt.yaml
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yaml
  cloud:
    nacos:
      server-addr: lirendada.art:8848
      discovery:
        server-addr: lirendada.art:8848
        namespace: ceaffba5-fad9-4149-a71a-f77956f10897
      config:
        server-addr: lirendada.art:8848
        namespace: ceaffba5-fad9-4149-a71a-f77956f10897
        file-extension: yaml

xxl:
  job:
    admin:
      # 调度中心部署跟地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。
      addresses: http://127.0.0.1:8080/xxl-job-admin
    executor:
      # 执行器 AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
      appname: oj-job-executor
      # ✅ 新建议：使用 Mac/Linux 的临时目录
      # 这样日志会写到系统临时区，重启电脑可能会清空，完全不占用你的项目空间
      logpath: /tmp/xxl-job/jobhandler

      # 配合自动清理，只保留最近 3 天，几乎不占空间
      logretentiondays: 3
    accessToken: default_token # [选填]：调度中心通讯TOKEN [选填]：非空时启用；