server:
  port: 8002

spring:
  application:
    name: judge-service
  profiles:
    active: dev
  config:
    import:
      - optional:nacos:common.yaml
      - optional:nacos:jwt.yaml
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yaml
  cloud:
    nacos:
      server-addr: lirendada.art:8848
      discovery:
        server-addr: lirendada.art:8848
        namespace: ceaffba5-fad9-4149-a71a-f77956f10897
      config:
        server-addr: lirendada.art:8848
        namespace: ceaffba5-fad9-4149-a71a-f77956f10897
        file-extension: yaml

# 判题沙箱配置 (保留原有的)
oj:
  judge:
    docker:
      host: tcp://49.235.136.223:2375